### ISSUE TITLE
Feature request: support save generated image to a `Vec<u8>`

### ISSUE THREAD

**Issue by al8n** [conways-glider/identicon-rs#34]
Hi, thanks for the great crate.

Sometimes we may need to save the generated image in memory and store it in memory, instead of `save_to_file`.

**Comment by conways-glider** [comment]
Thank you for your request - I'll begin work on this soon!

**Comment by conways-glider** [comment]
Hello! I believe that `export_png_data` and `export_jpeg_data` may be what you're looking for. Can you check on that and see if that's what you need?

This functionality is in the [examples/webserver.rs](https://github.com/conways-glider/identicon-rs/blob/v4.0.1/examples/webserver.rs) example.

**Comment by al8n** [comment]
Thanks! It is actually what I need.
