### ISSUE TITLE
All above 1.0 versions were yanked

### ISSUE THREAD

**Issue by dns2utf8** [conways-glider/identicon-rs#8]
Dear @fluffy-samurai 

Thank you for the work you put into identicon-rs to make it work.
I was very surprised to see that all releases after 0.2.2 have been yanked.
Was there a reason for that?

Cheers,
Stefan

**Comment by conways-glider** [comment]
Sorry for any confusion - this has now been fixed! Looks like a bad external CI job was running from another project. 

Thank you for pointing this out!

**Comment by dns2utf8** [comment]
No problem, thank you for fixing it so quickly!

Cheers
